# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/chris/Documents/papinhio-player/ui/menu-3/scheduled-transmitions/errors-and-warnings/scheduled-transmitions.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(899, 248)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("QFrame{border:0px;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_label = QtWidgets.QLabel(self.frame)
        self.image_label.setMaximumSize(QtCore.QSize(117, 117))
        self.image_label.setText("")
        self.image_label.setPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/information.png"))
        self.image_label.setScaledContents(True)
        self.image_label.setObjectName("image_label")
        self.horizontalLayout.addWidget(self.image_label)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.yes_when_right_time = QtWidgets.QPushButton(Dialog)
        self.yes_when_right_time.setObjectName("yes_when_right_time")
        self.gridLayout.addWidget(self.yes_when_right_time, 1, 0, 1, 1)
        self.yes_no = QtWidgets.QPushButton(Dialog)
        self.yes_no.setObjectName("yes_no")
        self.gridLayout.addWidget(self.yes_no, 2, 0, 1, 1)
        self.ignore_scheduled_transmition = QtWidgets.QPushButton(Dialog)
        self.ignore_scheduled_transmition.setObjectName("ignore_scheduled_transmition")
        self.gridLayout.addWidget(self.ignore_scheduled_transmition, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Προγραμματισμένες μεταδόσεις"))
        self.label.setText(_translate("Dialog", "Έχει προγραμματιστεί η προγραμματισμένη μετάδοση με τίτλο:\n"
" \"...\" για ... δηλαδή σε 1 λεπτό.\n"
"Παρακαλώ αποφασίστε αν θα γίνει εισαγωγή των δεδομένων της στην λίστα αναπαραγωγής του main player."))
        self.yes_when_right_time.setText(_translate("Dialog", "Ναι (όταν φτάσει η κατάλληλη στιγμή)"))
        self.yes_no.setText(_translate("Dialog", "Ναι (αμέσως τώρα)"))
        self.ignore_scheduled_transmition.setText(_translate("Dialog", "Όχι"))
import sys
sys.path.append('../../../')

import importlib
icons = importlib.import_module('icons')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
