# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/chris/Documents/papinhio-player/ui/main-window/messages/ip-calls.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(662, 248)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/telephone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("QFrame{border:0px;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_label = QtWidgets.QLabel(self.frame)
        self.image_label.setMaximumSize(QtCore.QSize(117, 117))
        self.image_label.setText("")
        self.image_label.setPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/telephone.png"))
        self.image_label.setScaledContents(True)
        self.image_label.setObjectName("image_label")
        self.horizontalLayout.addWidget(self.image_label)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.local_answer = QtWidgets.QPushButton(Dialog)
        self.local_answer.setObjectName("local_answer")
        self.gridLayout.addWidget(self.local_answer, 1, 0, 1, 1)
        self.public_answer = QtWidgets.QPushButton(Dialog)
        self.public_answer.setObjectName("public_answer")
        self.gridLayout.addWidget(self.public_answer, 2, 0, 1, 1)
        self.ignore_call = QtWidgets.QPushButton(Dialog)
        self.ignore_call.setObjectName("ignore_call")
        self.gridLayout.addWidget(self.ignore_call, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.local_answer, self.public_answer)
        Dialog.setTabOrder(self.public_answer, self.ignore_call)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ηχητική κλήση"))
        self.label.setText(_translate("Dialog", "Έχετε τηλεφωνική κλήση από τον χρήστη ... ... .\n"
"Παρακαλώ διαχειριστείτε την κλήση με τους ακόλουθους τρόπους:"))
        self.local_answer.setText(_translate("Dialog", "Απάντηση (τοπικά)"))
        self.public_answer.setText(_translate("Dialog", "Απάντηση (και εκτροπή κλήσης στον αέρα)"))
        self.ignore_call.setText(_translate("Dialog", "Απόρριψη"))
import sys
sys.path.append('../../')

import importlib
icons = importlib.import_module('icons')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
