# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/chris/Documents/papinhio-player/ui/menu-1/usefull-repeated/station-logos/import/import.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(746, 349)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("QFrame{border:none;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_and_preview = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_and_preview.sizePolicy().hasHeightForWidth())
        self.save_and_preview.setSizePolicy(sizePolicy)
        self.save_and_preview.setMinimumSize(QtCore.QSize(0, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_and_preview.setIcon(icon1)
        self.save_and_preview.setObjectName("save_and_preview")
        self.horizontalLayout.addWidget(self.save_and_preview)
        self.cancel = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel.sizePolicy().hasHeightForWidth())
        self.cancel.setSizePolicy(sizePolicy)
        self.cancel.setMinimumSize(QtCore.QSize(0, 0))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.gridLayout.addWidget(self.frame, 5, 0, 1, 2)
        self.rating_frame = QtWidgets.QFrame(Dialog)
        self.rating_frame.setStyleSheet("QFrame{border:none;}")
        self.rating_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rating_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rating_frame.setObjectName("rating_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.rating_frame)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout.addWidget(self.rating_frame, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.is_default = QtWidgets.QCheckBox(Dialog)
        self.is_default.setText("")
        self.is_default.setObjectName("is_default")
        self.gridLayout.addWidget(self.is_default, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.description = QtWidgets.QPlainTextEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description.sizePolicy().hasHeightForWidth())
        self.description.setSizePolicy(sizePolicy)
        self.description.setMinimumSize(QtCore.QSize(0, 0))
        self.description.setStyleSheet("QPlainTextEdit{border:1px solid #ABABAB;}")
        self.description.setObjectName("description")
        self.gridLayout.addWidget(self.description, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.title = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setMinimumSize(QtCore.QSize(0, 0))
        self.title.setDragEnabled(True)
        self.title.setClearButtonEnabled(True)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setStyleSheet("QLabel{\n"
"    font-weight:bold;\n"
"    color:green;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.title, self.description)
        Dialog.setTabOrder(self.description, self.is_default)
        Dialog.setTabOrder(self.is_default, self.save_and_preview)
        Dialog.setTabOrder(self.save_and_preview, self.cancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Εισαγωγή σήματος σταθμού"))
        self.save_and_preview.setText(_translate("Dialog", "Αποθήκευση και προεπισκόπηση"))
        self.cancel.setText(_translate("Dialog", "Ακύρωση"))
        self.label.setText(_translate("Dialog", "Τίτλος σήματος σταθμού:"))
        self.label_2.setText(_translate("Dialog", "Περιγραφή:"))
        self.label_4.setText(_translate("Dialog", "Προεπιλεγμένο σήμα σταθμού:"))
        self.description.setPlaceholderText(_translate("Dialog", "Πληκτρολογήστε την περιγραφή για το ηχητικό σήμα σταθμού."))
        self.label_3.setText(_translate("Dialog", "Αξιολόγηση:"))
        self.title.setPlaceholderText(_translate("Dialog", "Τίτλος σήματος σταθμού"))
        self.label_5.setText(_translate("Dialog", "Σημείωση: Όλα τα πεδία είναι υποχρεωτικά."))
import sys
sys.path.append('../../../../')

import importlib
icons = importlib.import_module('compiled-ui.icons')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
