# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/chris/Documents/papinhio-player/ui/menu-1/manage-radio-transmitions/manage-radio-transmitions.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(811, 352)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/radio-stations.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 809, 350))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radio_titles_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.radio_titles_frame.setStyleSheet("QFrame{border:none;}")
        self.radio_titles_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.radio_titles_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.radio_titles_frame.setObjectName("radio_titles_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.radio_titles_frame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4.addWidget(self.radio_titles_frame, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 158, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.disconnect_all = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disconnect_all.sizePolicy().hasHeightForWidth())
        self.disconnect_all.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/disconnect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.disconnect_all.setIcon(icon1)
        self.disconnect_all.setObjectName("disconnect_all")
        self.gridLayout_4.addWidget(self.disconnect_all, 4, 0, 1, 1)
        self.ok = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok.sizePolicy().hasHeightForWidth())
        self.ok.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ok.setIcon(icon2)
        self.ok.setObjectName("ok")
        self.gridLayout_4.addWidget(self.ok, 5, 0, 1, 1)
        self.connect_all = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connect_all.sizePolicy().hasHeightForWidth())
        self.connect_all.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/start-transmition.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connect_all.setIcon(icon3)
        self.connect_all.setObjectName("connect_all")
        self.gridLayout_4.addWidget(self.connect_all, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setStyleSheet("QLabel{\n"
"    font-weight:bold;\n"
"    color:green;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 2, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.scrollArea, self.connect_all)
        Dialog.setTabOrder(self.connect_all, self.disconnect_all)
        Dialog.setTabOrder(self.disconnect_all, self.ok)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Διαχείριση ραδιοφωνικών μεταδόσεων"))
        self.disconnect_all.setText(_translate("Dialog", "Αποσύνδεση από όλους τους ανωτέρω ραδιοφωνικούς σταθμούς"))
        self.ok.setText(_translate("Dialog", "Εντάξει"))
        self.connect_all.setText(_translate("Dialog", "Σύνδεση σε όλους τους ανωτέρω ραδιοφωνικούς σταθμούς"))
        self.label.setText(_translate("Dialog", "Σημείωση: Θα ενημερωθείτε με κατάλληλο μήνυμα σε περίπτωση απροσδόκητης διακοπής ραδιοφωνικής σύνδεσης και γενικότερα σε περίπτωσεις σφαλμάτων."))
import sys
sys.path.append('../../')

import importlib
icons = importlib.import_module('compiled-ui.icons')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
