# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/chris/Documents/papinhio-player/ui/menu-1/sound-files/import-sound-file-from-video/import-sound-file-from-video.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(820, 229)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/import-video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.select_local_video = QtWidgets.QPushButton(self.tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/select-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.select_local_video.setIcon(icon1)
        self.select_local_video.setObjectName("select_local_video")
        self.gridLayout_2.addWidget(self.select_local_video, 0, 0, 1, 2)
        self.local_video_progressBar = QtWidgets.QProgressBar(self.tab)
        self.local_video_progressBar.setProperty("value", 0)
        self.local_video_progressBar.setObjectName("local_video_progressBar")
        self.gridLayout_2.addWidget(self.local_video_progressBar, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setStyleSheet("QLabel{\n"
"    font-weight:bold;\n"
"    color:green;\n"
"}")
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.download_progressBar = QtWidgets.QProgressBar(self.tab_2)
        self.download_progressBar.setProperty("value", 0)
        self.download_progressBar.setObjectName("download_progressBar")
        self.gridLayout_3.addWidget(self.download_progressBar, 1, 1, 1, 1)
        self.youtube_url = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.youtube_url.sizePolicy().hasHeightForWidth())
        self.youtube_url.setSizePolicy(sizePolicy)
        self.youtube_url.setDragEnabled(True)
        self.youtube_url.setClearButtonEnabled(True)
        self.youtube_url.setObjectName("youtube_url")
        self.gridLayout_3.addWidget(self.youtube_url, 0, 0, 1, 1)
        self.download_and_export_video_from_youtube = QtWidgets.QPushButton(self.tab_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.download_and_export_video_from_youtube.setIcon(icon2)
        self.download_and_export_video_from_youtube.setObjectName("download_and_export_video_from_youtube")
        self.gridLayout_3.addWidget(self.download_and_export_video_from_youtube, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.youtube_convert_progressBar = QtWidgets.QProgressBar(self.tab_2)
        self.youtube_convert_progressBar.setProperty("value", 0)
        self.youtube_convert_progressBar.setObjectName("youtube_convert_progressBar")
        self.gridLayout_3.addWidget(self.youtube_convert_progressBar, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setStyleSheet("QLabel{\n"
"    font-weight:bold;\n"
"    color:green;\n"
"}")
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.select_local_video)
        Dialog.setTabOrder(self.select_local_video, self.youtube_url)
        Dialog.setTabOrder(self.youtube_url, self.download_and_export_video_from_youtube)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Εισαγωγή αρχείου ήχου από βίντεο"))
        self.label.setText(_translate("Dialog", "Ποσοστό εξαγωγής αρχείου ήχου:"))
        self.select_local_video.setText(_translate("Dialog", "Επιλογή τοπικού αρχείου video"))
        self.label_4.setText(_translate("Dialog", "Σημείωση: Μετά το πέρας της εισαγωγής θα ανοιξει το παράθυρο \"Εισαγωγή αρχείου ήχου\" για την επεξεργασία των πληροφοριών του αρχείου ήχου (όπως καλλιτέχνης, στιχουργός και συνθέτης)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Εισαγωγή ήχου από τοπικό αρχείο video"))
        self.youtube_url.setPlaceholderText(_translate("Dialog", "Εισαγωγή youtube διεύθυνσης"))
        self.download_and_export_video_from_youtube.setText(_translate("Dialog", "Λήψη αρχείου video και εξαγωγή ήχου από το youtube"))
        self.label_2.setText(_translate("Dialog", "Ποσοστό λήψης:"))
        self.label_3.setText(_translate("Dialog", "Ποσοστό εξαγωγής αρχείου ήχου:"))
        self.label_5.setText(_translate("Dialog", "Σημείωση: Μετά το πέρας της λήψης και της εξαγωγής θα ανοιξει το παράθυρο \"Εισαγωγή αρχείου ήχου\" για την επεξεργασία των πληροφοριών του αρχείου ήχου (όπως καλλιτέχνης, στιχουργός και συνθέτης)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Εισαγωγή video από το youtube"))
import sys
sys.path.append('../../../')

import importlib
icons = importlib.import_module('compiled-ui.icons')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
