# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/chris/Documents/papinhio-player/ui/menu-1/usefull-repeated/Greece-time/edit/unique-title.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(696, 184)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("QFrame{border:0px;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_label = QtWidgets.QLabel(self.frame)
        self.image_label.setMaximumSize(QtCore.QSize(117, 117))
        self.image_label.setText("")
        self.image_label.setPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/information.png"))
        self.image_label.setScaledContents(True)
        self.image_label.setObjectName("image_label")
        self.horizontalLayout.addWidget(self.image_label)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.edit_title = QtWidgets.QPushButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.edit_title.setIcon(icon1)
        self.edit_title.setObjectName("edit_title")
        self.gridLayout.addWidget(self.edit_title, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Σφάλμα στην διεργασία επεξεργασίας συλλογής Ώρας Ελλάδας"))
        self.label.setText(_translate("Dialog", "Ο τίτλος της συλλογής Ώρας Ελλάδας που επιλέξατε (\"...\") δεν μπορεί να χρησιμοποιηθεί διότι έχετε επιλέξει τον ίδιο τίτλο για άλλη συλλογή Ώρας Ελλάδας. Επιλέξτε κάποιον άλλον και έπειτα προσπαθήστε ξανά."))
        self.edit_title.setText(_translate("Dialog", "Τροποποίηση τίτλου"))
import sys
sys.path.append('../../../../')

import importlib
icons = importlib.import_module('icons')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
