# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/chris/Documents/papinhio-player/ui/menu-1/reports/scheduled-transmition-report/scheduled-transmition-report.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 204)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/scheduled-transmitions-report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.select_scheduled_transmition = QtWidgets.QComboBox(Dialog)
        self.select_scheduled_transmition.setObjectName("select_scheduled_transmition")
        self.select_scheduled_transmition.addItem("")
        self.gridLayout.addWidget(self.select_scheduled_transmition, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.start_datetime = QtWidgets.QDateTimeEdit(Dialog)
        self.start_datetime.setCalendarPopup(True)
        self.start_datetime.setObjectName("start_datetime")
        self.gridLayout.addWidget(self.start_datetime, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.end_datetime = QtWidgets.QDateTimeEdit(Dialog)
        self.end_datetime.setCalendarPopup(True)
        self.end_datetime.setObjectName("end_datetime")
        self.gridLayout.addWidget(self.end_datetime, 2, 1, 1, 1)
        self.radio_connections_frame = QtWidgets.QFrame(Dialog)
        self.radio_connections_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.radio_connections_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.radio_connections_frame.setObjectName("radio_connections_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.radio_connections_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.radio_connections_frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.radio_connections_frame, 3, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setStyleSheet("QLabel{\n"
"    font-weight:bold;\n"
"    color:green;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 2)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("QFrame{border:none;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.create_report_and_close = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_report_and_close.sizePolicy().hasHeightForWidth())
        self.create_report_and_close.setSizePolicy(sizePolicy)
        self.create_report_and_close.setIcon(icon)
        self.create_report_and_close.setObjectName("create_report_and_close")
        self.horizontalLayout.addWidget(self.create_report_and_close)
        self.cancel = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel.sizePolicy().hasHeightForWidth())
        self.cancel.setSizePolicy(sizePolicy)
        self.cancel.setMinimumSize(QtCore.QSize(0, 0))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.gridLayout.addWidget(self.frame, 5, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.select_scheduled_transmition, self.start_datetime)
        Dialog.setTabOrder(self.start_datetime, self.end_datetime)
        Dialog.setTabOrder(self.end_datetime, self.create_report_and_close)
        Dialog.setTabOrder(self.create_report_and_close, self.cancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Αναφορά προγραμματισμένης μετάδοσης"))
        self.label.setText(_translate("Dialog", "Επιλογή προγραμματισμένης μετάδοσης:"))
        self.select_scheduled_transmition.setItemText(0, _translate("Dialog", "Επιλέξτε μία προγραμματισμένη μετάδοση"))
        self.label_2.setText(_translate("Dialog", "Ημερομηνία έναρξης:"))
        self.label_3.setText(_translate("Dialog", "Ημερομηνία λήξης:"))
        self.label_5.setText(_translate("Dialog", "Επιλέξτε ραδιοφωνικές συνδέσεις."))
        self.label_4.setText(_translate("Dialog", "Σημείωση: Θα ενημερωθείτε με μήνυμα όταν η αναφορά είναι έτοιμη."))
        self.create_report_and_close.setText(_translate("Dialog", "Δημιουργία αναφοράς σε μορφή .pdf και κλείσιμο παραθύρου"))
        self.cancel.setText(_translate("Dialog", "Ακύρωση"))
import sys
sys.path.append('../../../')

import importlib
icons = importlib.import_module('icons')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
