# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/chris/Documents/papinhio-player/ui/menu-1/retransmitions/errors/wrong-internet-address.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(690, 439)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("QFrame{border:0px;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_label = QtWidgets.QLabel(self.frame)
        self.image_label.setMinimumSize(QtCore.QSize(117, 117))
        self.image_label.setMaximumSize(QtCore.QSize(117, 117))
        self.image_label.setText("")
        self.image_label.setPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/information.png"))
        self.image_label.setScaledContents(True)
        self.image_label.setObjectName("image_label")
        self.horizontalLayout.addWidget(self.image_label)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.details = QtWidgets.QPlainTextEdit(Dialog)
        self.details.setObjectName("details")
        self.gridLayout.addWidget(self.details, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 3, 0, 1, 1)
        self.ok = QtWidgets.QPushButton(Dialog)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ok.setIcon(icon3)
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 4, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.details, self.pushButton)
        Dialog.setTabOrder(self.pushButton, self.pushButton_2)
        Dialog.setTabOrder(self.pushButton_2, self.ok)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Σφάλμα στην διεργασία εισαγωγής αναμετάδοσης"))
        self.label.setText(_translate("Dialog", "Η διεύθυνση Internet του ραδιοφωνικού σταθμού ... είναι λάθος. Επεξεργαστείτε την ραδιοφωνική αναμετάδοση ώστε να εισάγετε έγκυρες ρυθμίσεις Internet ή διαγράψτε την ραδιοφωνική αναμετάδοση από την δισκοθήκη."))
        self.pushButton.setText(_translate("Dialog", "Επεξεργασία αναμετάδοσης"))
        self.pushButton_2.setText(_translate("Dialog", "Διαγραφή αναμετάδοσης"))
        self.ok.setText(_translate("Dialog", "Εντάξει - Παράλειψη"))
import sys
sys.path.append('../../../')

import importlib
icons = importlib.import_module('compiled-ui.icons')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
