# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/chris/Documents/papinhio-player/ui/menu-1/record/start-record.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(934, 103)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/main-window/assets/images/main-window/record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("QFrame{border:none;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_record = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_record.sizePolicy().hasHeightForWidth())
        self.start_record.setSizePolicy(sizePolicy)
        self.start_record.setMinimumSize(QtCore.QSize(0, 0))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/main-window/assets/images/main-window/start-recording.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_record.setIcon(icon1)
        self.start_record.setObjectName("start_record")
        self.horizontalLayout.addWidget(self.start_record)
        self.cancel = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel.sizePolicy().hasHeightForWidth())
        self.cancel.setSizePolicy(sizePolicy)
        self.cancel.setMinimumSize(QtCore.QSize(0, 0))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(7, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.filename = QtWidgets.QLineEdit(Dialog)
        self.filename.setStyleSheet("QLineEdit{\n"
"    border-top:1px solid #ABABAB;\n"
"    border-bottom:1px solid #ABABAB;\n"
"    border-left:1px solid #ABABAB;\n"
"    border-right:none;\n"
"}")
        self.filename.setInputMask("")
        self.filename.setDragEnabled(True)
        self.filename.setClearButtonEnabled(True)
        self.filename.setObjectName("filename")
        self.gridLayout.addWidget(self.filename, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.filename_suffix = QtWidgets.QLabel(Dialog)
        self.filename_suffix.setStyleSheet("QLabel{\n"
"    background-color:white;\n"
"    border-top:1px solid #ABABAB;\n"
"    border-bottom:1px solid #ABABAB;\n"
"    border-right:1px solid #ABABAB;\n"
"    padding:0px;\n"
"    margin:0px;\n"
"    line-height:auto;\n"
"}")
        self.filename_suffix.setObjectName("filename_suffix")
        self.gridLayout.addWidget(self.filename_suffix, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setStyleSheet("QLabel{\n"
"    font-weight:bold;\n"
"    color:green;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.filename, self.start_record)
        Dialog.setTabOrder(self.start_record, self.cancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Έναρξη ηχογράφησης"))
        self.start_record.setText(_translate("Dialog", "Έναρξη ηχογράφησης"))
        self.cancel.setText(_translate("Dialog", "Ακύρωση"))
        self.filename.setPlaceholderText(_translate("Dialog", "Πληκτρολογήστε εδώ το όνομα του αρχείου ηχογράφησης."))
        self.label.setText(_translate("Dialog", "Όνομα αρχείου ηχογράφησης:"))
        self.filename_suffix.setText(_translate("Dialog", "_datetime.mp3"))
        self.label_2.setText(_translate("Dialog", "Σημείωση: Στο όνομα του αρχείου ηχογράφησης θα προστεθεί η σημερινή ημερομηνία σε μορφή timestamp (_YYYY-MM-DD.mp3)"))
import sys
sys.path.append('../../')

import importlib
icons = importlib.import_module('compiled-ui.icons')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
