# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/chris/Documents/papinhio-player/ui/menu-3/scheduled-transmitions/explore/scheduled-transmitions.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1916, 1052)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.table = QtWidgets.QTableWidget(Dialog)
        self.table.setStyleSheet("QTableWidget{border:1px solid #ABABAB;}")
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setAlternatingRowColors(True)
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table.setRowCount(0)
        self.table.setObjectName("table")
        self.table.setColumnCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(8, item)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setHighlightSections(False)
        self.table.horizontalHeader().setMinimumSectionSize(260)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setHighlightSections(False)
        self.gridLayout.addWidget(self.table, 0, 0, 1, 3)
        self.add_new = QtWidgets.QPushButton(Dialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/add-circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_new.setIcon(icon1)
        self.add_new.setObjectName("add_new")
        self.gridLayout.addWidget(self.add_new, 1, 0, 1, 1)
        self.activate_all = QtWidgets.QPushButton(Dialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/activate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.activate_all.setIcon(icon2)
        self.activate_all.setObjectName("activate_all")
        self.gridLayout.addWidget(self.activate_all, 1, 1, 1, 1)
        self.deactivate_all = QtWidgets.QPushButton(Dialog)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/deactivate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deactivate_all.setIcon(icon3)
        self.deactivate_all.setObjectName("deactivate_all")
        self.gridLayout.addWidget(self.deactivate_all, 1, 2, 1, 1)
        self.ok = QtWidgets.QPushButton(Dialog)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/rest-windows/assets/images/rest-windows/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ok.setIcon(icon4)
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 2, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.table, self.add_new)
        Dialog.setTabOrder(self.add_new, self.activate_all)
        Dialog.setTabOrder(self.activate_all, self.deactivate_all)
        Dialog.setTabOrder(self.deactivate_all, self.ok)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Επεξεργασία προγραμματισμένων μεταδόσεων"))
        self.table.setSortingEnabled(False)
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Τίτλος"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Τύποι"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Κατάσταση"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Ημερομηνία έναρξης"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "New Column"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Παράμετροι επανάληψης"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Ημερομηνία λήξης"))
        item = self.table.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Επόμενη εκτέλεση"))
        item = self.table.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Ενέργειες"))
        self.add_new.setText(_translate("Dialog", "Προσθήκη νέας προγραμματισμένης μετάδοσης"))
        self.activate_all.setText(_translate("Dialog", "Ενεργοποίηση όλων"))
        self.deactivate_all.setText(_translate("Dialog", "Απενεργοποίηση όλων"))
        self.ok.setText(_translate("Dialog", "Εντάξει - Κλείσιμο παραθύρου"))
import sys
sys.path.append('../../../')

import importlib
icons = importlib.import_module('compiled-ui.icons')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
